<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>7d6fad56-d5eb-4c37-b9b7-51d4669701b7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.4.6" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Identity\PassingTrace.Identity.AuthorizationServer\PassingTrace.Identity.AuthorizationServer.csproj" />
  </ItemGroup>

</Project>
