<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Aspire.StackExchange.Redis" />
    <PackageReference Include="DistributedLock.Redis" />
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="Microsoft.Agents.AI" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" />
    <PackageReference Include="ModelContextProtocol" />
    <PackageReference Include="Pgvector.EntityFrameworkCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\PassingTrace.Core\PassingTrace.Core.csproj" />
    <ProjectReference Include="..\..\PassingTrace.Infrastructure\PassingTrace.Infrastructure.csproj" />
  </ItemGroup>
</Project>
