// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PassingTrace.Infrastructure;

#nullable disable

namespace PassingTrace.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TraceDbContext))]
    [Migration("20260818071845_InitialTrace")]
    partial class InitialTrace
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PassingTrace.Core.Events.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentSourceRevision")
                        .HasColumnType("integer")
                        .HasColumnName("current_source_revision");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EventKind")
                        .HasColumnType("integer")
                        .HasColumnName("event_kind");

                    b.Property<DateTimeOffset?>("HappenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("happened_at");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset?>("PlannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_at");

                    b.Property<string>("RawContent")
                        .HasColumnType("text")
                        .HasColumnName("raw_content");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_trace_event_user_id");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uk_trace_event_user_idempotency")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("UserId", "DeletedAt", "CreatedAt")
                        .HasDatabaseName("ix_trace_event_user_created");

                    b.ToTable("trace_event", null, t =>
                        {
                            t.HasComment("用户自由记录与计划的事实源，Trace 与 Plan 统一抽象。");
                        });
                });

            modelBuilder.Entity("PassingTrace.Core.Events.SourceRevision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset?>("HappenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("happened_at");

                    b.Property<DateTimeOffset?>("PlannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_at");

                    b.Property<string>("RawContent")
                        .HasColumnType("text")
                        .HasColumnName("raw_content");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Revision")
                        .IsUnique()
                        .HasDatabaseName("uk_event_source_revision_event_revision");

                    b.ToTable("event_source_revision", null, t =>
                        {
                            t.HasComment("Event 的 Source 修订快照，旧值永不原地覆盖。");
                        });
                });

            modelBuilder.Entity("PassingTrace.Core.Events.SourceRevision", b =>
                {
                    b.HasOne("PassingTrace.Core.Events.Event", "Event")
                        .WithMany("SourceRevisions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("PassingTrace.Core.Events.Event", b =>
                {
                    b.Navigation("SourceRevisions");
                });
#pragma warning restore 612, 618
        }
    }
}
