// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using PassingTrace.Infrastructure;
using Pgvector;

#nullable disable

namespace PassingTrace.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TraceDbContext))]
    [Migration("20260830085035_AddSemanticRelationships")]
    partial class AddSemanticRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PassingTrace.Core.Ai.AiConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DeletedAt", "UpdatedAt")
                        .HasDatabaseName("ix_ai_conversation_user_updated");

                    b.ToTable("ai_conversation", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.AiMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("DataWatermark")
                        .HasColumnType("bigint")
                        .HasColumnName("data_watermark");

                    b.Property<string>("EvidenceSnapshotJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence_snapshot");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("prompt_version");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("UserId", "ConversationId", "Id")
                        .HasDatabaseName("ix_ai_message_user_conversation");

                    b.ToTable("ai_message", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.ConversationSummary", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<long>("ThroughMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("through_message_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("ConversationId");

                    b.ToTable("conversation_summary", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.EventSearchIndex", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AiSummary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_summary");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<string>("ImageDescriptions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_descriptions");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_content");

                    b.Property<string>("RetrievalText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("retrieval_text");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('simple', coalesce(retrieval_text, ''))", true);

                    b.Property<long?>("SemanticRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("semantic_run_id");

                    b.Property<int>("SourceRevision")
                        .HasColumnType("integer")
                        .HasColumnName("source_revision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_event_search_index_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("RetrievalText")
                        .HasDatabaseName("ix_event_search_index_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("RetrievalText"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("RetrievalText"), new[] { "gin_trgm_ops" });

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_event_search_index_fts");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("UserId", "IsCurrent")
                        .HasDatabaseName("ix_event_search_index_user_current");

                    b.HasIndex("UserId", "EventId", "SourceRevision")
                        .IsUnique()
                        .HasDatabaseName("uk_event_search_index_user_event_revision");

                    b.ToTable("event_search_index", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.EventSemanticRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("DurationMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("error_message");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("PipelineVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pipeline_version");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("schema_version");

                    b.Property<string>("SemanticEnvelopeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("semantic_envelope");

                    b.Property<int>("SourceRevision")
                        .HasColumnType("integer")
                        .HasColumnName("source_revision");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "SourceRevision", "PipelineVersion")
                        .HasDatabaseName("ix_semantic_run_event_revision_pipeline");

                    b.HasIndex("UserId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_semantic_run_user_status_created");

                    b.ToTable("event_semantic_run", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.ExpenseFact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("amount");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("currency");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("purpose");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("scope");

                    b.Property<long>("SemanticRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("semantic_run_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SemanticRunId");

                    b.HasIndex("UserId", "Currency")
                        .HasDatabaseName("ix_expense_fact_user_currency");

                    b.ToTable("expense_fact", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<string>("LastError")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("lease_owner");

                    b.Property<Guid?>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("message_type");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int?>("SourceRevision")
                        .HasColumnType("integer")
                        .HasColumnName("source_revision");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "SourceRevision", "MessageType")
                        .HasDatabaseName("ix_outbox_event_revision_type");

                    b.HasIndex("Status", "AvailableAt", "Priority")
                        .HasDatabaseName("ix_outbox_claim");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.SemanticMention", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Assertion")
                        .HasColumnType("integer")
                        .HasColumnName("assertion");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<Guid?>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("normalized_value");

                    b.Property<string>("OriginalValue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("original_value");

                    b.Property<long>("SemanticRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("semantic_run_id");

                    b.Property<int?>("TextLength")
                        .HasColumnType("integer")
                        .HasColumnName("text_length");

                    b.Property<int?>("TextStart")
                        .HasColumnType("integer")
                        .HasColumnName("text_start");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SemanticRunId");

                    b.HasIndex("UserId", "Category", "NormalizedValue")
                        .HasDatabaseName("ix_semantic_mention_user_category_value");

                    b.ToTable("semantic_mention", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.UserDataWatermark", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("UserId");

                    b.ToTable("user_data_watermark", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.UserMemory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("memory_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_user_memory_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("UserId", "Fingerprint")
                        .IsUnique()
                        .HasDatabaseName("uk_user_memory_user_fingerprint");

                    b.HasIndex("UserId", "Status", "UpdatedAt")
                        .HasDatabaseName("ix_user_memory_user_status_updated");

                    b.ToTable("user_memory", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.UserMemoryEvidence", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence");

                    b.Property<long>("SemanticRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("semantic_run_id");

                    b.Property<int>("SourceRevision")
                        .HasColumnType("integer")
                        .HasColumnName("source_revision");

                    b.Property<long>("UserMemoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_memory_id");

                    b.HasKey("Id");

                    b.HasIndex("UserMemoryId", "EventId", "SourceRevision")
                        .IsUnique()
                        .HasDatabaseName("uk_user_memory_evidence_source");

                    b.ToTable("user_memory_evidence", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Events.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentSourceRevision")
                        .HasColumnType("integer")
                        .HasColumnName("current_source_revision");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EventKind")
                        .HasColumnType("integer")
                        .HasColumnName("event_kind");

                    b.Property<DateTimeOffset?>("HappenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("happened_at");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset?>("PlannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_at");

                    b.Property<string>("RawContent")
                        .HasColumnType("text")
                        .HasColumnName("raw_content");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_trace_event_user_id");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uk_trace_event_user_idempotency")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("UserId", "DeletedAt", "CreatedAt")
                        .HasDatabaseName("ix_trace_event_user_created");

                    b.ToTable("trace_event", null, t =>
                        {
                            t.HasComment("用户自由记录与计划的事实源，Trace 与 Plan 统一抽象。");
                        });
                });

            modelBuilder.Entity("PassingTrace.Core.Events.SourceRevision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset?>("HappenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("happened_at");

                    b.Property<DateTimeOffset?>("PlannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_at");

                    b.Property<string>("RawContent")
                        .HasColumnType("text")
                        .HasColumnName("raw_content");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Revision")
                        .IsUnique()
                        .HasDatabaseName("uk_event_source_revision_event_revision");

                    b.ToTable("event_source_revision", null, t =>
                        {
                            t.HasComment("Event 的 Source 修订快照，旧值永不原地覆盖。");
                        });
                });

            modelBuilder.Entity("PassingTrace.Core.Media.EventMediaAsset", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("EventId", "MediaAssetId");

                    b.HasIndex("MediaAssetId");

                    b.HasIndex("EventId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("uk_event_media_asset_order");

                    b.ToTable("event_media_asset", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Media.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActualSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("actual_sha256");

                    b.Property<long?>("ActualSize")
                        .HasColumnType("bigint")
                        .HasColumnName("actual_size");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeclaredMimeType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("declared_mime_type");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ExpectedSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("expected_sha256");

                    b.Property<long>("ExpectedSize")
                        .HasColumnType("bigint")
                        .HasColumnName("expected_size");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("MultipartUploadId")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("multipart_upload_id");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("object_key");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("ProcessingError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("processing_error");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset>("UploadExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upload_expires_at");

                    b.Property<int>("UploadMode")
                        .HasColumnType("integer")
                        .HasColumnName("upload_mode");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("VerifiedMimeType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("verified_mime_type");

                    b.HasKey("Id");

                    b.HasIndex("ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("uk_media_asset_object_key");

                    b.HasIndex("UserId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_media_asset_user_status_created");

                    b.ToTable("media_asset", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Media.SourceRevisionMedia", b =>
                {
                    b.Property<long>("SourceRevisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_revision_id");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("SourceRevisionId", "MediaAssetId");

                    b.HasIndex("MediaAssetId");

                    b.HasIndex("SourceRevisionId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("uk_event_source_revision_media_order");

                    b.ToTable("event_source_revision_media", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.AiMessage", b =>
                {
                    b.HasOne("PassingTrace.Core.Ai.AiConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.ConversationSummary", b =>
                {
                    b.HasOne("PassingTrace.Core.Ai.AiConversation", "Conversation")
                        .WithOne("Summary")
                        .HasForeignKey("PassingTrace.Core.Ai.ConversationSummary", "ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.EventSemanticRun", b =>
                {
                    b.HasOne("PassingTrace.Core.Events.Event", "Event")
                        .WithMany("SemanticRuns")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.ExpenseFact", b =>
                {
                    b.HasOne("PassingTrace.Core.Ai.EventSemanticRun", "SemanticRun")
                        .WithMany("Expenses")
                        .HasForeignKey("SemanticRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SemanticRun");
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.OutboxMessage", b =>
                {
                    b.HasOne("PassingTrace.Core.Events.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Event");
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.SemanticMention", b =>
                {
                    b.HasOne("PassingTrace.Core.Ai.EventSemanticRun", "SemanticRun")
                        .WithMany("Mentions")
                        .HasForeignKey("SemanticRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SemanticRun");
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.UserMemoryEvidence", b =>
                {
                    b.HasOne("PassingTrace.Core.Ai.UserMemory", "UserMemory")
                        .WithMany("Evidence")
                        .HasForeignKey("UserMemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserMemory");
                });

            modelBuilder.Entity("PassingTrace.Core.Events.SourceRevision", b =>
                {
                    b.HasOne("PassingTrace.Core.Events.Event", "Event")
                        .WithMany("SourceRevisions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("PassingTrace.Core.Media.EventMediaAsset", b =>
                {
                    b.HasOne("PassingTrace.Core.Events.Event", "Event")
                        .WithMany("MediaAssets")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PassingTrace.Core.Media.MediaAsset", "MediaAsset")
                        .WithMany("EventLinks")
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("MediaAsset");
                });

            modelBuilder.Entity("PassingTrace.Core.Media.SourceRevisionMedia", b =>
                {
                    b.HasOne("PassingTrace.Core.Media.MediaAsset", "MediaAsset")
                        .WithMany("RevisionLinks")
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PassingTrace.Core.Events.SourceRevision", "SourceRevision")
                        .WithMany("MediaAssets")
                        .HasForeignKey("SourceRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaAsset");

                    b.Navigation("SourceRevision");
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.AiConversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Summary");
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.EventSemanticRun", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Mentions");
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.UserMemory", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("PassingTrace.Core.Events.Event", b =>
                {
                    b.Navigation("MediaAssets");

                    b.Navigation("SemanticRuns");

                    b.Navigation("SourceRevisions");
                });

            modelBuilder.Entity("PassingTrace.Core.Events.SourceRevision", b =>
                {
                    b.Navigation("MediaAssets");
                });

            modelBuilder.Entity("PassingTrace.Core.Media.MediaAsset", b =>
                {
                    b.Navigation("EventLinks");

                    b.Navigation("RevisionLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
