// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using PassingTrace.Infrastructure;
using Pgvector;

#nullable disable

namespace PassingTrace.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TraceDbContext))]
    [Migration("20260901140134_AddStorylines")]
    partial class AddStorylines
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PassingTrace.Core.Ai.AiConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DeletedAt", "UpdatedAt")
                        .HasDatabaseName("ix_ai_conversation_user_updated");

                    b.ToTable("ai_conversation", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.AiMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("DataWatermark")
                        .HasColumnType("bigint")
                        .HasColumnName("data_watermark");

                    b.Property<string>("EvidenceSnapshotJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence_snapshot");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("prompt_version");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("UserId", "ConversationId", "Id")
                        .HasDatabaseName("ix_ai_message_user_conversation");

                    b.ToTable("ai_message", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.ConversationSummary", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<long>("ThroughMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("through_message_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("ConversationId");

                    b.ToTable("conversation_summary", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.EventSearchIndex", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AiSummary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_summary");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<string>("ImageDescriptions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_descriptions");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_content");

                    b.Property<string>("RetrievalText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("retrieval_text");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('simple', coalesce(retrieval_text, ''))", true);

                    b.Property<long?>("SemanticRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("semantic_run_id");

                    b.Property<int>("SourceRevision")
                        .HasColumnType("integer")
                        .HasColumnName("source_revision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_event_search_index_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("EventId");

                    b.HasIndex("RetrievalText")
                        .HasDatabaseName("ix_event_search_index_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("RetrievalText"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("RetrievalText"), new[] { "gin_trgm_ops" });

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_event_search_index_fts");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("UserId", "IsCurrent")
                        .HasDatabaseName("ix_event_search_index_user_current");

                    b.HasIndex("UserId", "EventId", "SourceRevision")
                        .IsUnique()
                        .HasDatabaseName("uk_event_search_index_user_event_revision");

                    b.ToTable("event_search_index", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.EventSemanticRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("DurationMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("error_message");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("PipelineVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pipeline_version");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("schema_version");

                    b.Property<string>("SemanticEnvelopeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("semantic_envelope");

                    b.Property<int>("SourceRevision")
                        .HasColumnType("integer")
                        .HasColumnName("source_revision");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "SourceRevision", "PipelineVersion")
                        .HasDatabaseName("ix_semantic_run_event_revision_pipeline");

                    b.HasIndex("UserId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_semantic_run_user_status_created");

                    b.ToTable("event_semantic_run", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.ExpenseFact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("amount");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("currency");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("purpose");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("scope");

                    b.Property<long>("SemanticRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("semantic_run_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SemanticRunId");

                    b.HasIndex("UserId", "Currency")
                        .HasDatabaseName("ix_expense_fact_user_currency");

                    b.ToTable("expense_fact", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<string>("LastError")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("lease_owner");

                    b.Property<Guid?>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("message_type");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int?>("SourceRevision")
                        .HasColumnType("integer")
                        .HasColumnName("source_revision");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "SourceRevision", "MessageType")
                        .HasDatabaseName("ix_outbox_event_revision_type");

                    b.HasIndex("Status", "AvailableAt", "Priority")
                        .HasDatabaseName("ix_outbox_claim");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.SemanticMention", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Assertion")
                        .HasColumnType("integer")
                        .HasColumnName("assertion");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<Guid?>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("normalized_value");

                    b.Property<string>("OriginalValue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("original_value");

                    b.Property<long>("SemanticRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("semantic_run_id");

                    b.Property<int?>("TextLength")
                        .HasColumnType("integer")
                        .HasColumnName("text_length");

                    b.Property<int?>("TextStart")
                        .HasColumnType("integer")
                        .HasColumnName("text_start");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SemanticRunId");

                    b.HasIndex("UserId", "Category", "NormalizedValue")
                        .HasDatabaseName("ix_semantic_mention_user_category_value");

                    b.ToTable("semantic_mention", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.UserDataWatermark", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("UserId");

                    b.ToTable("user_data_watermark", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.UserMemory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("memory_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_user_memory_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("UserId", "Fingerprint")
                        .IsUnique()
                        .HasDatabaseName("uk_user_memory_user_fingerprint");

                    b.HasIndex("UserId", "Status", "UpdatedAt")
                        .HasDatabaseName("ix_user_memory_user_status_updated");

                    b.ToTable("user_memory", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.UserMemoryEvidence", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence");

                    b.Property<long>("SemanticRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("semantic_run_id");

                    b.Property<int>("SourceRevision")
                        .HasColumnType("integer")
                        .HasColumnName("source_revision");

                    b.Property<long>("UserMemoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_memory_id");

                    b.HasKey("Id");

                    b.HasIndex("UserMemoryId", "EventId", "SourceRevision")
                        .IsUnique()
                        .HasDatabaseName("uk_user_memory_evidence_source");

                    b.ToTable("user_memory_evidence", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Events.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentSourceRevision")
                        .HasColumnType("integer")
                        .HasColumnName("current_source_revision");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EventKind")
                        .HasColumnType("integer")
                        .HasColumnName("event_kind");

                    b.Property<DateTimeOffset?>("HappenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("happened_at");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset?>("PlannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_at");

                    b.Property<string>("RawContent")
                        .HasColumnType("text")
                        .HasColumnName("raw_content");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_trace_event_user_id");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uk_trace_event_user_idempotency")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("UserId", "DeletedAt", "CreatedAt")
                        .HasDatabaseName("ix_trace_event_user_created");

                    b.ToTable("trace_event", null, t =>
                        {
                            t.HasComment("用户自由记录与计划的事实源，Trace 与 Plan 统一抽象。");
                        });
                });

            modelBuilder.Entity("PassingTrace.Core.Events.EventLabelIndex", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("normalized_value");

                    b.Property<int>("Origin")
                        .HasColumnType("integer")
                        .HasColumnName("origin");

                    b.Property<long?>("SemanticRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("semantic_run_id");

                    b.Property<int>("SourceRevision")
                        .HasColumnType("integer")
                        .HasColumnName("source_revision");

                    b.Property<string>("TaxonomyKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("taxonomy_key");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("label_type");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId", "EventId", "SourceRevision", "NormalizedValue")
                        .HasDatabaseName("uk_event_label_event_revision_value");

                    b.HasIndex("UserId", "Type", "TaxonomyKey", "IsCurrent")
                        .HasDatabaseName("ix_event_label_user_type_key_current");

                    b.ToTable("event_label_index", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Events.EventLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AccuracyMeters")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("accuracy_meters");

                    b.Property<string>("AdCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("ad_code");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset?>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<string>("City")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("city");

                    b.Property<string>("CoordinateSystem")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("coordinate_system");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("District")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("district");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("PoiType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("poi_type");

                    b.Property<string>("ProviderPoiId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_poi_id");

                    b.Property<string>("Province")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("province");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<int>("SourceRevision")
                        .HasColumnType("integer")
                        .HasColumnName("source_revision");

                    b.Property<long>("SourceRevisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_revision_id");

                    b.Property<bool>("UserConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("user_confirmed");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("SourceRevisionId");

                    b.HasIndex("UserId", "AdCode")
                        .HasDatabaseName("ix_event_location_user_adcode");

                    b.HasIndex("UserId", "EventId", "SourceRevision")
                        .HasDatabaseName("ix_event_location_user_event_revision");

                    b.ToTable("event_location", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Events.SourceRevision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset?>("HappenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("happened_at");

                    b.Property<DateTimeOffset?>("PlannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_at");

                    b.Property<string>("RawContent")
                        .HasColumnType("text")
                        .HasColumnName("raw_content");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Revision")
                        .IsUnique()
                        .HasDatabaseName("uk_event_source_revision_event_revision");

                    b.ToTable("event_source_revision", null, t =>
                        {
                            t.HasComment("Event 的 Source 修订快照，旧值永不原地覆盖。");
                        });
                });

            modelBuilder.Entity("PassingTrace.Core.Events.SourceRevisionLabel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Decision")
                        .HasColumnType("integer")
                        .HasColumnName("decision");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("normalized_value");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<long>("SourceRevisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_revision_id");

                    b.Property<string>("TaxonomyKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("taxonomy_key");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("label_type");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SourceRevisionId");

                    b.HasIndex("UserId", "NormalizedValue")
                        .HasDatabaseName("ix_source_label_user_value");

                    b.ToTable("source_revision_label", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Events.UserPlace", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AdCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("ad_code");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("address");

                    b.Property<string>("CanonicalKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("canonical_key");

                    b.Property<string>("CoordinateSystem")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("coordinate_system");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<DateTimeOffset>("FirstVisitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_visited_at");

                    b.Property<DateTimeOffset>("LastVisitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_visited_at");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("ProviderPoiId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_poi_id");

                    b.Property<string>("RetrievalText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("retrieval_text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<int>("VisitCount")
                        .HasColumnType("integer")
                        .HasColumnName("visit_count");

                    b.HasKey("Id");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_user_place_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("UserId", "CanonicalKey")
                        .IsUnique()
                        .HasDatabaseName("uk_user_place_user_key");

                    b.ToTable("user_place", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Media.EventMediaAsset", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("EventId", "MediaAssetId");

                    b.HasIndex("MediaAssetId");

                    b.HasIndex("EventId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("uk_event_media_asset_order");

                    b.ToTable("event_media_asset", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Media.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActualSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("actual_sha256");

                    b.Property<long?>("ActualSize")
                        .HasColumnType("bigint")
                        .HasColumnName("actual_size");

                    b.Property<string>("AiObjectKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("ai_object_key");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeclaredMimeType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("declared_mime_type");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ExpectedSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("expected_sha256");

                    b.Property<long>("ExpectedSize")
                        .HasColumnType("bigint")
                        .HasColumnName("expected_size");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("MultipartUploadId")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("multipart_upload_id");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("object_key");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("ProcessingError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("processing_error");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("ThumbnailObjectKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("thumbnail_object_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset>("UploadExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upload_expires_at");

                    b.Property<int>("UploadMode")
                        .HasColumnType("integer")
                        .HasColumnName("upload_mode");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("VerifiedMimeType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("verified_mime_type");

                    b.HasKey("Id");

                    b.HasIndex("ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("uk_media_asset_object_key");

                    b.HasIndex("UserId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_media_asset_user_status_created");

                    b.ToTable("media_asset", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Media.SourceRevisionMedia", b =>
                {
                    b.Property<long>("SourceRevisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_revision_id");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("SourceRevisionId", "MediaAssetId");

                    b.HasIndex("MediaAssetId");

                    b.HasIndex("SourceRevisionId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("uk_event_source_revision_media_order");

                    b.ToTable("event_source_revision_media", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Storylines.Storyline", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("CategoryKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category_key");

                    b.Property<Guid?>("CoverMediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("cover_media_asset_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreationIdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("creation_idempotency_key");

                    b.Property<int>("CurrentRevision")
                        .HasColumnType("integer")
                        .HasColumnName("current_revision");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("RangeEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("range_end");

                    b.Property<DateTimeOffset?>("RangeStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("range_start");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreationIdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uk_storyline_user_creation_idempotency")
                        .HasFilter("creation_idempotency_key IS NOT NULL");

                    b.HasIndex("UserId", "CategoryKey", "Status")
                        .HasDatabaseName("ix_storyline_user_category_status");

                    b.HasIndex("UserId", "DeletedAt", "UpdatedAt")
                        .HasDatabaseName("ix_storyline_user_updated");

                    b.ToTable("storyline", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Storylines.StorylineEdge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid")
                        .HasColumnName("edge_key");

                    b.Property<string>("Label")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("label");

                    b.Property<int>("RelationType")
                        .HasColumnType("integer")
                        .HasColumnName("relation_type");

                    b.Property<Guid>("SourceNodeKey")
                        .HasColumnType("uuid")
                        .HasColumnName("source_node_key");

                    b.Property<long>("StorylineRevisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("storyline_revision_id");

                    b.Property<Guid>("TargetNodeKey")
                        .HasColumnType("uuid")
                        .HasColumnName("target_node_key");

                    b.HasKey("Id");

                    b.HasIndex("StorylineRevisionId", "Key")
                        .IsUnique()
                        .HasDatabaseName("uk_storyline_edge_key");

                    b.HasIndex("StorylineRevisionId", "SourceNodeKey", "TargetNodeKey", "RelationType")
                        .IsUnique()
                        .HasDatabaseName("uk_storyline_edge_relation");

                    b.ToTable("storyline_edge", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Storylines.StorylineNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Emphasis")
                        .HasColumnType("integer")
                        .HasColumnName("emphasis");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid")
                        .HasColumnName("node_key");

                    b.Property<int>("SemanticOrder")
                        .HasColumnType("integer")
                        .HasColumnName("semantic_order");

                    b.Property<int>("SourceRevision")
                        .HasColumnType("integer")
                        .HasColumnName("source_revision");

                    b.Property<Guid?>("StageKey")
                        .HasColumnType("uuid")
                        .HasColumnName("stage_key");

                    b.Property<long>("StorylineRevisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("storyline_revision_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("StorylineRevisionId", "EventId")
                        .IsUnique()
                        .HasDatabaseName("uk_storyline_node_event");

                    b.HasIndex("StorylineRevisionId", "Key")
                        .IsUnique()
                        .HasDatabaseName("uk_storyline_node_key");

                    b.ToTable("storyline_node", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Storylines.StorylineRevision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category_key");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<Guid?>("CoverMediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("cover_media_asset_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<int>("LayoutState")
                        .HasColumnType("integer")
                        .HasColumnName("layout_state");

                    b.Property<DateTimeOffset?>("RangeEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("range_end");

                    b.Property<DateTimeOffset?>("RangeStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("range_start");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("StorylineId")
                        .HasColumnType("uuid")
                        .HasColumnName("storyline_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("StorylineId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uk_storyline_revision_idempotency")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("StorylineId", "Revision")
                        .IsUnique()
                        .HasDatabaseName("uk_storyline_revision_number");

                    b.ToTable("storyline_revision", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Storylines.StorylineRevisionTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("display_name");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("normalized_value");

                    b.Property<int>("Origin")
                        .HasColumnType("integer")
                        .HasColumnName("origin");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<long>("StorylineRevisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("storyline_revision_id");

                    b.Property<string>("TaxonomyKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("taxonomy_key");

                    b.HasKey("Id");

                    b.HasIndex("StorylineRevisionId", "NormalizedValue")
                        .IsUnique()
                        .HasDatabaseName("uk_storyline_revision_tag");

                    b.ToTable("storyline_revision_tag", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Storylines.StorylineSearchIndex", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<string>("RetrievalText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("retrieval_text");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('simple', coalesce(retrieval_text, ''))", true);

                    b.Property<Guid>("StorylineId")
                        .HasColumnType("uuid")
                        .HasColumnName("storyline_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_storyline_search_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("RetrievalText")
                        .HasDatabaseName("ix_storyline_search_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("RetrievalText"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("RetrievalText"), new[] { "gin_trgm_ops" });

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_storyline_search_fts");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("StorylineId");

                    b.HasIndex("UserId", "IsCurrent")
                        .HasDatabaseName("ix_storyline_search_current");

                    b.HasIndex("UserId", "StorylineId", "Revision")
                        .IsUnique()
                        .HasDatabaseName("uk_storyline_search_revision");

                    b.ToTable("storyline_search_index", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Storylines.StorylineStage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid")
                        .HasColumnName("stage_key");

                    b.Property<int>("SemanticOrder")
                        .HasColumnType("integer")
                        .HasColumnName("semantic_order");

                    b.Property<long>("StorylineRevisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("storyline_revision_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("StorylineRevisionId", "Key")
                        .IsUnique()
                        .HasDatabaseName("uk_storyline_stage_key");

                    b.ToTable("storyline_stage", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Storylines.StorylineWebLayout", b =>
                {
                    b.Property<long>("StorylineRevisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("storyline_revision_id");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("direction");

                    b.Property<decimal>("ViewportX")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("viewport_x");

                    b.Property<decimal>("ViewportY")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("viewport_y");

                    b.Property<decimal>("Zoom")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("zoom");

                    b.HasKey("StorylineRevisionId");

                    b.ToTable("storyline_web_layout", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Storylines.StorylineWebNodeLayout", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Height")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("height");

                    b.Property<Guid>("NodeKey")
                        .HasColumnType("uuid")
                        .HasColumnName("node_key");

                    b.Property<long>("StorylineRevisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("storyline_revision_id");

                    b.Property<decimal?>("Width")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("width");

                    b.Property<decimal>("X")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("x");

                    b.Property<decimal>("Y")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("y");

                    b.HasKey("Id");

                    b.HasIndex("StorylineRevisionId", "NodeKey")
                        .IsUnique()
                        .HasDatabaseName("uk_storyline_web_node_layout");

                    b.ToTable("storyline_web_node_layout", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Storylines.StorylineWebStageLayout", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Height")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("height");

                    b.Property<Guid>("StageKey")
                        .HasColumnType("uuid")
                        .HasColumnName("stage_key");

                    b.Property<long>("StorylineRevisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("storyline_revision_id");

                    b.Property<decimal>("Width")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("width");

                    b.Property<decimal>("X")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("x");

                    b.Property<decimal>("Y")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("y");

                    b.HasKey("Id");

                    b.HasIndex("StorylineRevisionId", "StageKey")
                        .IsUnique()
                        .HasDatabaseName("uk_storyline_web_stage_layout");

                    b.ToTable("storyline_web_stage_layout", (string)null);
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.AiMessage", b =>
                {
                    b.HasOne("PassingTrace.Core.Ai.AiConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.ConversationSummary", b =>
                {
                    b.HasOne("PassingTrace.Core.Ai.AiConversation", "Conversation")
                        .WithOne("Summary")
                        .HasForeignKey("PassingTrace.Core.Ai.ConversationSummary", "ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.EventSearchIndex", b =>
                {
                    b.HasOne("PassingTrace.Core.Events.Event", "Event")
                        .WithMany("SearchIndexes")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.EventSemanticRun", b =>
                {
                    b.HasOne("PassingTrace.Core.Events.Event", "Event")
                        .WithMany("SemanticRuns")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.ExpenseFact", b =>
                {
                    b.HasOne("PassingTrace.Core.Ai.EventSemanticRun", "SemanticRun")
                        .WithMany("Expenses")
                        .HasForeignKey("SemanticRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SemanticRun");
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.OutboxMessage", b =>
                {
                    b.HasOne("PassingTrace.Core.Events.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Event");
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.SemanticMention", b =>
                {
                    b.HasOne("PassingTrace.Core.Ai.EventSemanticRun", "SemanticRun")
                        .WithMany("Mentions")
                        .HasForeignKey("SemanticRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SemanticRun");
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.UserMemoryEvidence", b =>
                {
                    b.HasOne("PassingTrace.Core.Ai.UserMemory", "UserMemory")
                        .WithMany("Evidence")
                        .HasForeignKey("UserMemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserMemory");
                });

            modelBuilder.Entity("PassingTrace.Core.Events.EventLabelIndex", b =>
                {
                    b.HasOne("PassingTrace.Core.Events.Event", "Event")
                        .WithMany("LabelIndexes")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("PassingTrace.Core.Events.EventLocation", b =>
                {
                    b.HasOne("PassingTrace.Core.Events.Event", "Event")
                        .WithMany("Locations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PassingTrace.Core.Events.SourceRevision", "Revision")
                        .WithMany("Locations")
                        .HasForeignKey("SourceRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("PassingTrace.Core.Events.SourceRevision", b =>
                {
                    b.HasOne("PassingTrace.Core.Events.Event", "Event")
                        .WithMany("SourceRevisions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("PassingTrace.Core.Events.SourceRevisionLabel", b =>
                {
                    b.HasOne("PassingTrace.Core.Events.SourceRevision", "SourceRevision")
                        .WithMany("Labels")
                        .HasForeignKey("SourceRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceRevision");
                });

            modelBuilder.Entity("PassingTrace.Core.Media.EventMediaAsset", b =>
                {
                    b.HasOne("PassingTrace.Core.Events.Event", "Event")
                        .WithMany("MediaAssets")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PassingTrace.Core.Media.MediaAsset", "MediaAsset")
                        .WithMany("EventLinks")
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("MediaAsset");
                });

            modelBuilder.Entity("PassingTrace.Core.Media.SourceRevisionMedia", b =>
                {
                    b.HasOne("PassingTrace.Core.Media.MediaAsset", "MediaAsset")
                        .WithMany("RevisionLinks")
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PassingTrace.Core.Events.SourceRevision", "SourceRevision")
                        .WithMany("MediaAssets")
                        .HasForeignKey("SourceRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaAsset");

                    b.Navigation("SourceRevision");
                });

            modelBuilder.Entity("PassingTrace.Core.Storylines.StorylineEdge", b =>
                {
                    b.HasOne("PassingTrace.Core.Storylines.StorylineRevision", "Revision")
                        .WithMany("Edges")
                        .HasForeignKey("StorylineRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("PassingTrace.Core.Storylines.StorylineNode", b =>
                {
                    b.HasOne("PassingTrace.Core.Events.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PassingTrace.Core.Storylines.StorylineRevision", "Revision")
                        .WithMany("Nodes")
                        .HasForeignKey("StorylineRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("PassingTrace.Core.Storylines.StorylineRevision", b =>
                {
                    b.HasOne("PassingTrace.Core.Storylines.Storyline", "Storyline")
                        .WithMany("Revisions")
                        .HasForeignKey("StorylineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Storyline");
                });

            modelBuilder.Entity("PassingTrace.Core.Storylines.StorylineRevisionTag", b =>
                {
                    b.HasOne("PassingTrace.Core.Storylines.StorylineRevision", "Revision")
                        .WithMany("Tags")
                        .HasForeignKey("StorylineRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("PassingTrace.Core.Storylines.StorylineSearchIndex", b =>
                {
                    b.HasOne("PassingTrace.Core.Storylines.Storyline", "Storyline")
                        .WithMany("SearchIndexes")
                        .HasForeignKey("StorylineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Storyline");
                });

            modelBuilder.Entity("PassingTrace.Core.Storylines.StorylineStage", b =>
                {
                    b.HasOne("PassingTrace.Core.Storylines.StorylineRevision", "Revision")
                        .WithMany("Stages")
                        .HasForeignKey("StorylineRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("PassingTrace.Core.Storylines.StorylineWebLayout", b =>
                {
                    b.HasOne("PassingTrace.Core.Storylines.StorylineRevision", "Revision")
                        .WithOne("WebLayout")
                        .HasForeignKey("PassingTrace.Core.Storylines.StorylineWebLayout", "StorylineRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("PassingTrace.Core.Storylines.StorylineWebNodeLayout", b =>
                {
                    b.HasOne("PassingTrace.Core.Storylines.StorylineWebLayout", "Layout")
                        .WithMany("Nodes")
                        .HasForeignKey("StorylineRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Layout");
                });

            modelBuilder.Entity("PassingTrace.Core.Storylines.StorylineWebStageLayout", b =>
                {
                    b.HasOne("PassingTrace.Core.Storylines.StorylineWebLayout", "Layout")
                        .WithMany("Stages")
                        .HasForeignKey("StorylineRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Layout");
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.AiConversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Summary");
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.EventSemanticRun", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Mentions");
                });

            modelBuilder.Entity("PassingTrace.Core.Ai.UserMemory", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("PassingTrace.Core.Events.Event", b =>
                {
                    b.Navigation("LabelIndexes");

                    b.Navigation("Locations");

                    b.Navigation("MediaAssets");

                    b.Navigation("SearchIndexes");

                    b.Navigation("SemanticRuns");

                    b.Navigation("SourceRevisions");
                });

            modelBuilder.Entity("PassingTrace.Core.Events.SourceRevision", b =>
                {
                    b.Navigation("Labels");

                    b.Navigation("Locations");

                    b.Navigation("MediaAssets");
                });

            modelBuilder.Entity("PassingTrace.Core.Media.MediaAsset", b =>
                {
                    b.Navigation("EventLinks");

                    b.Navigation("RevisionLinks");
                });

            modelBuilder.Entity("PassingTrace.Core.Storylines.Storyline", b =>
                {
                    b.Navigation("Revisions");

                    b.Navigation("SearchIndexes");
                });

            modelBuilder.Entity("PassingTrace.Core.Storylines.StorylineRevision", b =>
                {
                    b.Navigation("Edges");

                    b.Navigation("Nodes");

                    b.Navigation("Stages");

                    b.Navigation("Tags");

                    b.Navigation("WebLayout");
                });

            modelBuilder.Entity("PassingTrace.Core.Storylines.StorylineWebLayout", b =>
                {
                    b.Navigation("Nodes");

                    b.Navigation("Stages");
                });
#pragma warning restore 612, 618
        }
    }
}
